name: Main workflow
on: push
jobs:
  Build:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Clone down repository
        uses: actions/checkout@v4       
      - name: Build
        run: ci/build-app.sh
      - name: Test
        run: ci/unit-test-app.sh
      - name: Upload repo
        uses: actions/upload-artifact@v4
        with:
          name: code
          path: .
        
  Lint:
    runs-on: ubuntu-latest
    needs: [Build]
    container: gradle:6-jdk11
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with: 
          name: code
          path: .
      - name: Run linter
        uses: super-linter/super-linter/slim@5
        env: 
          DEFAULT_BRANCH : main
          GITHUB_TOKEN : ${{ secrets.GITHUB_TOKEN }}
          DISABLE_ERRORS: true  

